### PR TITLE
Edits from WebProtégé (alpha06_dev)

### PR DESCRIPTION
**Pull request by matuskalas**
Including various developments done between 5 Feb 2019 and 3 Mar 2020

Major contributions from members and guests of the COMULIS & NEUBIAS COST Actions

 * Added and refined topics and synonyms in sample preparation and tomography, and finalised coverage of imaging techniques (all of these to the high-level extent that influences choices of downstream analysis)
 * Created a concise but comprehensive ontology of Machine learning, Artificial intelligence, and Clustering (to the level relevant in particular in bioimaging, biosciences, but also scientific data analysis in general; left todo: operations related to training/parameter optimisation)
 * A couple of other editions - and a lot of refined annotation - in operations and topics
 * Work in progress (WIP) on definitions, rdfs:comments, and seeAlso links

Co-authored-by: Laure Plantard <plantard@mpi-cbg.de>
Co-authored-by: Joakim Lindblad (joakimlindblad) <joakim@cb.uu.se>
Co-authored-by: Martin Jones (martlj) <martin.jones@crick.ac.uk>
Co-authored-by: Nataša Sladoje <natasa.sladoje@it.uu.se>
Co-authored-by: Marie-Charlotte Domart <marie-charlotte.domart@crick.ac.uk>
Co-authored-by: Matthia Karreman <m.karreman@dkfz-heidelberg.de>
Co-authored-by: Arrate Muñoz-Barrutia <mamunozb@ing.uc3m.es>
Co-authored-by: Raf Van de Plas <raf.vandeplas@tudelft.nl>
Co-authored-by: Ivana Vrhovac Madunić <ivrhovac@imi.hr>
Co-authored-by: Dean Karaica <dkaraica@imi.hr>
Co-authored-by: Laura Nicolás Sáenz (lauranicolass) <lnicolas@ing.uc3m.es>
Co-authored-by: Estibaliz Gómez de Mariscal (esgomezm) <esgomezm@pa.uc3m.es>
Co-authored-by: Daniel Sage (dasv74) <daniel.sage@epfl.ch>
Co-authored-by: Robert Haase (haesleinhuepf) <rhaase@mpi-cbg.de>

### CODE REVIEW

**Review by matuskalas — COMMENTED** [review]
Looks great :-)

**Comment by joncison** [comment]
great to see things are happening ... a quick question - is editing in Protege standalone allowed, and if so, what is the workflow (editing token, updates etc.)?  Or should this all be done vie WebProtege?

**Comment by matuskalas** [comment]
@joncison: for now either commenting in WebProtégé (alpha07_dev), or an GH issue here, or a pull request here. Anything concrete in mind?

**Comment by joncison** [comment]
Cool, thanks.  Nothing concrete in mind, but I want to take a look after Lorentz.

**Pull request merged**
